### ISSUE TITLE
sass-lint does not fail on errors

### ISSUE THREAD

**Issue by alexdesignworks** [integratedexperts/drupal-dev#449]
errors are shown, but the exit code is `0`.

**Comment by alexdesignworks** [comment]
Checked and can confirm that sass-lint fails on errors and passes on warnings.

Since grunt-sass-lint project is not actively maintained, they will not provide a support for `--max-warnings: 0` CLI option for `sass-lint`.

Leaving this as is - any rules that need to be errors will have to change their code from `1` to `2` like so:

```yaml
...
# Rule Configuration
rules:
  indentation:
    - 2 # <----- Changed from '1' to '2' to make indentation violations to become errors.
    - size: 2
```
