### ISSUE TITLE
Updated deps.io config

### ISSUE THREAD

**Issue by alexdesignworks** [integratedexperts/drupal-dev#493]
```
version: 2
dependencies:
  - type: php
    path: /
    settings:
      composer_options: "--ignore-platform-reqs --no-progress --no-suggest"
      commit_message_prefix: "(bot) "
      related_pr_behavior: close
      github_labels:
        - dependencies
      github_assignees:
        - YOURNAME
    manifest_updates:
      filters:
        - name: ".*"
          versions: "L.Y.Y"

  - type: js
    path: /
    settings:
      commit_message_prefix: "(bot) "
      related_pr_behavior: close
      github_labels:
        - dependencies
      github_assignees:
        - YOURNAME
    manifest_updates:
      filters:
        - name: ".*"
          versions: "Y.Y.Y"

```
